[C] Fix variables in build scripts.

diff --git a/cppbuild/cppbuild b/cppbuild/cppbuild
--- a/cppbuild/cppbuild
+++ b/cppbuild/cppbuild
@@ -18,7 +18,7 @@ esac
 
 while [[ $# -gt 0 ]]
 do
-  option="$1"
+  option="${1}"
   case ${option} in
     --c-warnings-as-errors)
       EXTRA_CMAKE_ARGS="${EXTRA_CMAKE_ARGS} -DC_WARNINGS_AS_ERRORS=ON"
@@ -35,7 +35,8 @@ do
       shift
       ;;
     --slow-system-tests)
-      EXTRA_CMAKE_ARGS="${EXTRA_CMAKE_ARGS} -DAERON_SLOW_SYSTEM_TESTS=ON -DAERON_SYSTEM_TESTS=OFF"
+      EXTRA_CMAKE_ARGS="${EXTRA_CMAKE_ARGS} -DAERON_SLOW_SYSTEM_TESTS=ON"
+      echo "Enabling slow system tests"
       shift
       ;;
     -d|--debug-build)
@@ -74,34 +75,35 @@ do
       shift
       ;;
     -h|--help)
-      echo "$0 [--c-warnings-as-errors] [--cxx-warnings-as-errors] [--debug-build] [--build-aeron-driver] [--build-archive-api] [--sanitise-build] [--coverage-build] [--no-parallel] [--no-system-tests] [--slow-system-tests]"
+      echo "${0} [--c-warnings-as-errors] [--cxx-warnings-as-errors] [--debug-build] [--build-aeron-driver] [--build-archive-api] [--sanitise-build] [--coverage-build] [--no-parallel] [--no-system-tests] [--slow-system-tests]"
       exit
       ;;
     *)
-      echo "Unknown option $option"
+      echo "Unknown option ${option}"
       echo "Use --help for help"
       exit
       ;;
   esac
 done
 
-echo "Will make with \"-j $ncpus\"."
+echo "Will make with \"-j ${ncpus}\"."
 
 if [[ -d "${BUILD_DIR}" ]] ; then
-  echo "Build directory ($BUILD_DIR) exists, removing."
+  echo "Build directory (${BUILD_DIR}) exists, removing."
   rm -rf "${BUILD_DIR}"
 fi
 
 mkdir -p "${BUILD_DIR}"
 
-if [[ "${COVERAGE_BUILD}" -eq 1 ]] ; then
+if [[ ${COVERAGE_BUILD} -eq 1 ]] ; then
   cd "${BUILD_DIR}" || exit
-  cmake -G "Unix Makefiles" "${EXTRA_CMAKE_ARGS}" "${SOURCE_DIR}" && make clean && make -j "$ncpus" all && ctest -C ${BUILD_CONFIG} -j "$ncpus"
+  cmake -G "Unix Makefiles" ${EXTRA_CMAKE_ARGS} "${SOURCE_DIR}" && make clean && make -j ${ncpus} all && ctest -C ${BUILD_CONFIG} -j ${ncpus}
   rm -rf coverage
   mkdir -p coverage
   lcov --directory . --base-directory . --capture -o coverage/cov.info
   lcov -o coverage/cov.stripped.info --remove coverage/cov.info "/usr/include/*" "*/googletest/*" "*/test/cpp/*" "*/googlemock/*"
   genhtml coverage/cov.stripped.info --demangle-cpp -o coverage
 else
-  (cd "${BUILD_DIR}" && cmake -G "CodeBlocks - Unix Makefiles" "${EXTRA_CMAKE_ARGS}" "${SOURCE_DIR}" && make clean && make -j "$ncpus" all && ctest -C $BUILD_CONFIG --output-on-failure)
+  cd "${BUILD_DIR}" || exit
+  cmake -G "CodeBlocks - Unix Makefiles" ${EXTRA_CMAKE_ARGS} "${SOURCE_DIR}" && make clean && make -j ${ncpus} all && ctest -C ${BUILD_CONFIG} --output-on-failure
 fi
